### ISSUE TITLE
fwupdate version 11 issue on SuSE OS (SLED SP3)

### ISSUE THREAD

**Issue by Marc-Ila** [vathpela/fwup#120]
Since Suse OS does not have fwupdate or fwup packages , i am currently using packages released for OpenSuse. 

I am mostly doing manual update using fwupdate because this suse version is not supporting LVFS yet (AFAIK)

I could update firmware on the older versions but after updating to Version 11 (still Opensuse tumbleweed version) error message is returned when i use `fwupdate -a` :

`Could not set up firmware update: no such file or directory
error trace:
libfwup.c:1061 get_paths(): could not find fwup on ESP: no such file or directory
libfwup.c:1119 set_up_boot_next(): could not find paths for shim and fwup: no such file or directory
`

I did not encounter any error on other linux OS (ubuntu, RHEL7 and debian)that i have, but I realize version 11 isn't available yet for these OS 

Operating system and version: SuSE Linux Enterprise Desktop SP3 
Shim? : latest 14-3.1
How did you install fwupdate: via terminal (zypper install fwupdate)
Have you tried rebooting? Yes
Are you using an NVMe disk? no
Is secure boot enabled (only for the UEFI plugin)? no

Any guidance to resolve issue is greatly appreciated

**Comment by superm1** [comment]
You may need to manually install EFI application to EFI system partition. All those other distro do this automatically.

**Comment by Marc-Ila** [comment]
@superm1 Thank you very much for your reply.

I humbly apologize for my incompetence but unfortunately, i am not well versed with the solution provided. 
How does one execute such ?

**Comment by superm1** [comment]
Sorry this is super specific to how the package is built for which path it needs to go into. I would recommend you check with opensuse packagers to see what path they are expecting in the packaging.
