### ISSUE TITLE
nothing happens after reboot

### ISSUE THREAD

**Issue by emilas44** [vathpela/fwup#133]
Machine: X1 Extreme i7-8750H 16 GB RAM
OS: POP-OS 18.04
```
fwupdmgr --version
client version:	1.2.9
checkout info:	1.2.9
compile-time dependency versions
	gusb:	0.3.0
	efivar:	37
daemon version:	1.2.9
```

```
sudo fwupdmgr install 31c5f61ceb395c6a7379b3481f1560fe7dabe274-Lenovo-ThinkPad-P1X1Extreme-ConsumerMEFirmware-12.0.35.1427.cab
[sudo] password for elvis: 
Decompressing?           [***************************************]
Authenticating?          [***************************************]
Installing on UEFI Device Firmware?                              ]
Scheduling?              [***************************************]

An update requires a reboot to complete. Restart now? [Y|n]: 

```

I have a X1 Extreme and fwupdate does nothing after reboot.... if I run `fwupdmgr update` it downloads the update file and it asks if I want to reboot and If I type in Y and Enter it will reboot and comes normally up to login screen and does nothing. I even made a video so you guys can see it. Maybe someone can suggest something what can I try or do to make it work?

https://www.youtube.com/watch?v=awlPrj4YX0w

**Comment by hughsie** [comment]
I think you want the fwupd project rather than this one, but have you tried clearing all the system firmware settings back to defaults and then trying again? If that doesn't work please open a bug against fwupd and we can continue there.

**Comment by emilas44** [comment]
Can you please post the link for the 'fwupd' project
I thought this was the same thing.

**Comment by hughsie** [comment]
https://github.com/hughsie/fwupd/

**Comment by emilas44** [comment]
Moved to https://github.com/hughsie/fwupd/issues/1292
@hughsie  can we please continue the discussion on that link?
