### ISSUE TITLE
No updates to process, called in error, start_image: invalid parameter

### ISSUE THREAD

**Issue by lzap** [vathpela/fwup#137]
Hello,

my Fedora X1 laptop suffers from an incorrect behavior for some time. I have experienced this in Fedora 31, 30 (I believe) and now after I upgraded to 32 I still see the same.

I download updates via Gnome Software, reboot, enter boot entry selection (Enter + F12), pick Linux Update Firmware and I am getting this error. The laptop is connected to AC.

I do see four CAB files downloaded, however it is not starting up.

How can I troubleshoot this?

**Comment by superm1** [comment]
This project is discontinued, see the README.md for it.  Please file a bug here with all details from the template:
https://github.com/fwupd/fwupd/issues/new?assignees=&labels=bug&template=bug-report-uefi.md&title=
