### ISSUE TITLE
Same issue like fail to reboot into Ubuntu after successful update #86

### ISSUE THREAD

**Issue by motorbreth** [vathpela/fwup#139]
but it's Ubuntu 20.04.1 LTS upgraded from 18.04
Bios Version: 1.25.3
Dell Latitude E7470

**Comment by superm1** [comment]
This project isn't used in Ubuntu 20.04.  You're probably meaning https://github.com/fwupd/fwupd which is in Ubuntu 20.04.  Can you please file an update there?  Please fill out all the fields in the template:
https://github.com/fwupd/fwupd/issues/new?assignees=&labels=bug&template=bug-report-uefi.md&title=
