### ISSUE TITLE
help to "unharcode" paths for gnu-efi-lib to make fwupdate build in other distros

### ISSUE THREAD

**Issue by JotaRandom** [vathpela/fwup#3]
Not sure if this because fwupdate is not taking pkgconfig corretly or because the patch is hardcoded but make call /usr/lib/gnuefi//crt0-efi-ia32.o wich is different in some distros.
In Arch (yeah, I'm trying to  make a MAKEPKG for fwupdate for Arch) the path for crt0-efi-ia32.o in gnu-efi-lib is simply usr/lib/crt0-efi-ia32.o

gnu-efi in arch only have this [setup](https://projects.archlinux.org/svntogit/packages.git/plain/trunk/PKGBUILD?h=packages/gnu-efi-libs) therefor I can build fwupdate (from git) without seed magic, but that is plain wrong, so, some hints help?

**Comment by jared-dominguez** [comment]
Take a look at https://github.com/rhinstaller/fwupdate/commit/e36f2f23a1f197babde8caa485228c5cbfbd89a4 and https://github.com/rhinstaller/fwupdate/commit/727c4250bf343072a0912bc3dd77f4ef24103b60

You may also find these helpful:
http://linux.dell.com/cgi-bin/cgit.cgi/debian/fwupdate.git/tree/debian/rules
http://linux.dell.com/cgi-bin/cgit.cgi/debian/fwupdate.git/tree/debian/libfwup0.install
http://linux.dell.com/cgi-bin/cgit.cgi/debian/fwupdate.git/tree/debian/fwupdate.install

**Comment by mirco** [comment]
Also take a look at this package I added a couple hours ago:
https://aur4.archlinux.org/packages/fwupdate

**Comment by JotaRandom** [comment]
That package was not there when I post this.
let check but I thing all is fixed

**Comment by JotaRandom** [comment]
I talk so early
 libfwup.c:13:21: fatal error: efiboot.h: No such file or directory
efivar in arch install [usr/include/efivar/efiboot.h](https://www.archlinux.org/packages/testing/i686/efivar/files/) but look like either the stable and the git can't catch the path correctly

**Comment by jared-dominguez** [comment]
On Wed, Jun 24, 2015 at 09:34:45PM -0500,  Pablo Lezaeta Reyes [pˈaβ̞lo lˌe̞θaˈeta rˈejɛ] wrote:

> I talk so early
> libfwup.c:13:21: fatal error: efiboot.h: No such file or directory
> efivar in arch install usr/include/efivar/efiboot.h but look like either the
> stable and the git can't catch the path correctly

With which version of efivar are you building?

**Comment by JotaRandom** [comment]
Arch have in [core https://www.archlinux.org/packages/core/i686/efivar/]
efivars 0.15.
I not build any efivar, only i'm using the (for now) stock efivar in Arch.

2015-06-24 23:41 GMT-03:00 D. Jared Dominguez notifications@github.com:

> On Wed, Jun 24, 2015 at 09:34:45PM -0500, Pablo Lezaeta Reyes [pˈaβ̞lo
> lˌe̞θaˈeta rˈejɛ] wrote:
> 
> > I talk so early
> > libfwup.c:13:21: fatal error: efiboot.h: No such file or directory
> > efivar in arch install usr/include/efivar/efiboot.h but look like either
> > the
> > stable and the git can't catch the path correctly
> 
> With which version of efivar are you building?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rhinstaller/fwupdate/issues/3#issuecomment-115078229.

## 

_Pablo Lezaeta_

**Comment by jared-dominguez** [comment]
You need at least efivar 0.19 as noted in fwupdate.spec.in in the source tree.

-----Original Message-----

**Comment by vathpela** [comment]
Is this issue solved, then?
