### ISSUE TITLE
Canonical mini-audit

### ISSUE THREAD

**Issue by vathpela** [vathpela/fwup#32]
This isn't the full security audit we need - and in fact doesn't include the most important efi/ bits at all - but here's a list of stuff from https://bugs.launchpad.net/ubuntu/+source/fwupdate/+bug/1508926/comments/1 that should get addressed:
- ~~fwup_strerror_r() has unreachable statements, looks very buggy. Needs
  rewrite.~~ Fixed in 1e5a93f7419556103068a4de97b501b84ade205a
- ~~fwup_set_up_update() calls free(relpath) after calling relpath =
  onstack(relpath,...). This is a severe error.~~ fixed in e3b443d1
- ~~fwup_set_up_update() calls open(O_CREAT) without specifying permissions,
  the permissions will be set to garbage~~ Fixed in d9981cd5c2f5564c375834491a97fd53bd64804b
- ~~fwup_set_up_update() fullpath memory leak via open(fullpath...) error~~ fixed in e3b443d13836251dd15b091316858bb6d40a1f79
- ~~fwup_set_up_update() mkostemps() call does not need O_CREAT or O_RDWR~~ fixed in 70fb117c5386e2ff0908f9da2ed4526b010ffb9d
- ~~fwup_set_up_update() nested read()/write() loop is intricate; stdio.h
  fgetc() and fputc() loop with final fflush() might be easier to reason
  about and probably no less efficient.~~ Fixed in 05c06976ba71777da21feee2e3162e9c62883de4
- ~~fwup_set_up_update() probably needs a rewrite -- it is doing too much
  and its memory management is too confused which leads to a severe bug.~~ basically done in e3b443d13836251dd15b091316858bb6d40a1f79
- ~~extensive use of stack for storage; is stack able to handle the largest
  EFI variables?~~ As of cf409720e01eb6d27a466c60283149ac85d6a15c, within libfwup we only use the stack for short lived file paths.
- ~~put_info() does ssize_t arithmetic without checking for overflows -- how
  large will efidp_size() ever grow?~~ Fixed in cf409720e01eb6d27a466c60283149ac85d6a15c
- ~~get_info() free(local) may be called on uninitialized pointer if
  efi_get_variable() returns success but data_size < sizeof(*local)~~ Fixed as part of 1e5a93f7419556103068a4de97b501b84ade205a (woops)
- ~~fwup_resource_iter_create() memory leak if opendir() or dirfd() fail~~ Fixed in 389787c68245ed59ba3795de984b2f918fa4dbfe
- ~~utf8len() and ucs2len() handle limit=0 differently, > vs >=~~ fixed in 49746a9f96917420b8737c9cbec30d2c42257e43
- ~~utf8len() may read beyond the end of a malformed utf8 string that is
  shorter than limit~~ Not fixed; this is used only by utf8_to_ucs2(). See below.
- ~~utf8_to_ucs2() may read beyond the end of a malformed utf8 string that
  is shorter than max or may read beyond the end of utf8+max.~~ not fixed - this is used entirely on file paths that we're reasonably sure are not malformed.
- ~~print_system_resources() and main() have user-visible strings that aren't
  localized~~ Fixed in 87c7d60cc6236bb371e3f75f76edbbd17ba52d9d
- ~~delete_variable() contains unreachable code, is this a patch failure?~~ Doesn't appear to be true in any code I have...
- ~~All the signed files are signed by 'Red Hat Test Certificate" -- is this
  suitable for deployment?~~ No, no it's not.

**Comment by setharnold** [comment]
vathpela, thanks, this is great. The delete_variable() unreachable code was addressed by https://github.com/rhinstaller/fwupdate/commit/8139030084c51418778815ed283237553b1cec47

Thanks for the fixes!
