### ISSUE TITLE
MINOR_VERSION needs to be incremented to at least 5

### ISSUE THREAD

**Issue by superm1** [vathpela/fwup#33]
Due to this change in fwupd: 
https://github.com/hughsie/fwupd/commit/a941c3a9e919cd2ec45067ce14359bdd7404cce2 

MINOR_VERSION will need to be incremented to at least 5 to let fwupd still continue to compile.

**Comment by hughsie** [comment]
As a general note, I think targeting the 0_5_X branch would be sensible for now; that's what we're doing in F23.

**Comment by superm1** [comment]
Fixed with: https://github.com/rhinstaller/fwupdate/commit/03178919675d277178dc50c7c8941a9fd91e98ef
