### ISSUE TITLE
libfwupdate needs to be able to read the IEIT

### ISSUE THREAD

**Issue by vathpela** [vathpela/fwup#39]
We need to be able to tell if for some reason fwupdate did not get run, and IEIT will tell us that.

**Comment by superm1** [comment]
I think you need to change the milestone given the new versioning adoption you picked (1.1 < 7 :))

**Comment by vathpela** [comment]
(this is blocking on me writing IEIT code for the upstream kernel.)

**Comment by superm1** [comment]
https://github.com/rhboot/fwupdate/pull/136
