### ISSUE TITLE
Incorrect prefix for esrt_disabled and enable_esrt

### ISSUE THREAD

**Issue by hughsie** [vathpela/fwup#43]
We probably want to do something like:

```
enable_esrt() -> fwup_esrt_enable()
esrt_disabled() -> fwup_esrt_is_disabled()
```

Otherwise it's quite confusing where these symbols are coming from...

**Comment by vathpela** [comment]
Yeah, okay.

**Comment by superm1** [comment]
Thanks, saw you did that in https://github.com/rhinstaller/fwupdate/commit/b81771590044dabe10369bb95304274adabb279c.
I've made the associated changed for fwupd as well now.
https://github.com/hughsie/fwupd/commit/7ebdc1b1485a1e8eaef7d7bfa7f46517439121bf
