### ISSUE TITLE
fwup_set_up_update possibly needs fflush and fsync

### ISSUE THREAD

**Issue by superm1** [vathpela/fwup#46]
Another review happened in Ubuntu recently (https://bugs.launchpad.net/ubuntu/+source/fwupdate/+bug/1508926/comments/7) and one question was put forward that should be double checked:

```
fwup_set_up_update() lots of work between final fputc() and fclose() --
  does this need fflush(fout); fsync(outfd); before the work?
```

The remaining items from the review that were applicable are submitted in a pull request here: https://github.com/rhinstaller/fwupdate/pull/45/commits

**Comment by vathpela** [comment]
We don't need fflush(), as fclose() is defined as doing that, but we do need fsync() before we close the file.  Thanks!
