### ISSUE TITLE
fwupdate called in error, work laptop unbootable

### ISSUE THREAD

**Issue by vadi2** [vathpela/fwup#71]
I've originally reported this over at https://github.com/hughsie/fwupd/issues/152 and with continued research think this is a better place for it. 

I've applied two firmware updates using gnome software centre, but now the laptop is unbootable. How can I fix this?

**Comment by vadi2** [comment]
![img_20170701_063038](https://user-images.githubusercontent.com/110988/27759361-6712e930-5e2f-11e7-82a0-625ec20e039f.jpg)

**Comment by euxaristia** [comment]
What stage of boot is that?

Bios or OS?

**Comment by vadi2** [comment]
I'm not sure - this is after the Dell password needs to be put in and
before the Ubuntu encryption password.

**Comment by euxaristia** [comment]
Could you try a live usb?

**Comment by vadi2** [comment]
Try what?

**Comment by euxaristia** [comment]
A USB with a live system on it, like for example Ubuntu

**Comment by vadi2** [comment]
What would I do with it? Sorry, you haven't specified.

**Comment by euxaristia** [comment]
That would let you know how far the system can get in booting under the circumstances

**Comment by vadi2** [comment]
Resolved in https://github.com/hughsie/fwupd/issues/152 - the boot loader was incorrect. Thanks for looking at this!
