### ISSUE TITLE
add UEFI_GUID_IMAGE_UPLOAD to include headers

### ISSUE THREAD

**Issue by superm1** [vathpela/fwup#82]
So that fwupd can use it (per a discussion somewhere in https://github.com/hughsie/fwupd/pull/226)

**Comment by hughsie** [comment]
@superm1 can you do a PR for this pls?

**Comment by superm1** [comment]
`efi_guid_ux_capsule` ended up getting defined in efivar.  
It is probably better to have fwupd look at that.  I'll check that later.
I know efivar 33 is needed for it to work (or 32 + a patch).

**Comment by superm1** [comment]
I've submitted https://github.com/hughsie/fwupd/pull/361 for fixing this.
