### ISSUE TITLE
Add tag for version 10

### ISSUE THREAD

**Issue by mrueg** [vathpela/fwup#84]
https://github.com/rhboot/fwupdate/commit/9669ab00e23fbc2b9d77f538e797e5aef4a0138e mentions a bump to version 10, but it was never tagged. Can you add a tag?

**Comment by superm1** [comment]
Version 10 isn't out yet, that was just for preparing for when it is out

**Comment by ArchangeGabriel** [comment]
But Fedora published version 10 though…

**Comment by superm1** [comment]
Fedora has a git snapshot iirc. I know there are people complaining it doesn't flash, just reboots too.

**Comment by vathpela** [comment]
Done, thanks for the reminder.
