### ISSUE TITLE
Fail to reboot into Ubuntu after successful update

### ISSUE THREAD

**Issue by merlijn-sebrechts** [vathpela/fwup#86]
I triggered the update with Gnome Software on Ubuntu 17.10. Gnome Software asked me to restart, I click restart. During boot, the update starts correctly, and succeeds. After it succeeds, the laptop boots back into fwupd, which fails with the following error:

```
found update fwupdate-49w03513-7afe-49a-9d03-89e5ba1da865-0
fwupdate: No updates to process. Called in error?
start_image() returned Invalid Parameter
```

After a few seconds, it shows another screen:

```
No bootable devices found.
Press F1 key to retry boot.
Press F2 key to reboot into setup.
Press F5 key to run onboard diagnostics.
```

# Help, I've got this issue too and I can't boot!

I was able to workaround the issue by going into `setup`, `general > Boot Sequence`, and adding `grub64.efi` back as primary boot option.

**Picture walkthrough:**

When you see this message, press <kbd>F2</kbd> to enter the UEFI/BIOS setup.

<img src="https://user-images.githubusercontent.com/1492981/32445401-e149975e-c305-11e7-9b1c-0e0d800bb022.jpg" width="400">

Once in the setup, go to `general > Boot Sequence`.

<img src="https://user-images.githubusercontent.com/1492981/32445409-e5f482fa-c305-11e7-82b0-3dc19146eb08.jpg" width="400">

Click `Add boot option`.

<img src="https://user-images.githubusercontent.com/1492981/32445424-ef94c982-c305-11e7-8513-8b7ff2fda81e.jpg" width="400">

Call the boot option "Ubuntu" and click the three dots behind "filename".

<img src="https://user-images.githubusercontent.com/1492981/32445113-19ee5348-c305-11e7-8282-89992ca54441.jpg" width="400">

Choose the "grubx64.efi" file, click OK and add the boot option.

<img src="https://user-images.githubusercontent.com/1492981/32445124-2389ba32-c305-11e7-973c-3f92bbc41b09.jpg" width="400">

Now use the arrows to put the "Ubuntu" boot option to the top.

<img src="https://user-images.githubusercontent.com/1492981/32445261-7641438a-c305-11e7-9a9e-330824733938.jpg" width="400">

Save and exit, reboot and Ubuntu boots as normal!

**Comment by superm1** [comment]
Can you please share more details about your machine?  What model number? BIOS version you were at and version you were trying to upgrade to?

**Comment by merlijn-sebrechts** [comment]
Dell Latitude 5580, I was at 1.4.3 and upgraded to 1.6.4.

I've been trying to replicate this by downgrading and upgrading a few times, but I'm not able to replicate it anymore.

**Comment by superm1** [comment]
Hmm interesting.  to your first comment, a little more clarification:
When you say it starts successfully and succeeds, do you mean it flashed up to 1.6.4 and then didn't want to boot again?  or do you mean that fwupdate opened and that error came up?

**Comment by merlijn-sebrechts** [comment]
It flashed to 1.6.4 and it didn't boot again. (well it booted into those two error messages)

**Comment by superm1** [comment]
It sounds to me like you were missing a boot entry initially.  Were you booting using the removable media path \efi\boot\bootx64.efi?

**Comment by merlijn-sebrechts** [comment]
I don't know. It was a standard Ubuntu 17.10 installation.

Note that this was not the first upgrade I performed. The first one succeeded without issues, so I don't think it's an installation issue.

I downgraded the firmware manually using a USB stick and Dell's builtin firmware update utility, in order to reproduce some issues with the fwupdate integration in the software center. It was the first upgrade after this downgrade that failed.

**Comment by superm1** [comment]
Since this was with ubuntu 17.10, there's actually evidence logged into the journal log for fwupd.  can you look through journalctl to see if you have the `efibootmgr `output from before the update was performed?  It's been in fwupd 0.9.6 and later (17.10 has 0.9.7).

(Came from this commit: ) https://github.com/hughsie/fwupd/commit/f043f1f94b7f671e7e8d4fa3963a47e045d94f59

**Comment by merlijn-sebrechts** [comment]
No such luck, apparently Ubuntu 17.10 still doesn't enable persistent logs. Only the logs since last boot are visible. I configured persistent logs now, but that won't help much for this bug..

```
sudo journalctl --list-boots
 0 7318355f8d464ff7ae7d8f967466edd0 Tue 2017-10-24 09:11:37 CEST—Tue 2017-10-24 09:26:31 CEST
```

**Comment by superm1** [comment]
Ah well darn.

**Comment by gerobum** [comment]
Is this topic closes ? Because I have the same issue. Yesterday, I answered "yes" to the "update manager" which ask to me if I would like to change my firmware. And this morning, unable to boot on my ubuntu 
found update fwupdate-49w03513-7afe-49a-9d03-89e5ba1da865-0
fwupdate: No updates to process. Called in error?
start_image() returned Invalid Parameter

**Comment by merlijn-sebrechts** [comment]
@gerobum Do you have persistent logs on?

For reference,

- The fwupd bug in the Ubuntu launchpad: https://bugs.launchpad.net/fwupd/+bug/1730343
- The bug that persistent logs are disabled by default: https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1618188

**Comment by gerobum** [comment]
@galgalesh I don't what do you by "persistent logs on". But I don't know what to do because I am unable to boot.

Have you fixed your problem ?

**Comment by merlijn-sebrechts** [comment]
@gerobum Oh, why didn't you say that earlier! I added a picture guide to my original message on the top of this thread.

After fixing your installation, can you show the output of

```bash
 sudo journalctl --list-boots
```

to figure out if you have persistent logs enabled?

**Comment by gerobum** [comment]
@galgalesh Ok thanks. But I tried to do the same. Unfortunatly I have now directly this
No bootable devices found.
Press F1 key to retry boot.
Press F2 key to run onboard diagnostics.
Press F5 key to run onboard diagnostics.

**Comment by merlijn-sebrechts** [comment]
@gerobum can you show a picture of the "boot sequence screen"? (the last picture in my tutorial)

**Comment by galgalesh** [comment]
@gerobum a picture of the "boot menu" is also useful. You get that screen by furiously tapping <kbd>esc</kbd> after rebooting the laptop. Example shown below

<img src="https://user-images.githubusercontent.com/1492981/32446761-369cdc3a-c30a-11e7-91b2-9c8effa0042f.jpg" width="400">

**Comment by gerobum** [comment]
Thanks a lot. It works now.
When I type  sudo journalctl --list-boots, I have something like that
0 f4998...ae3b2f6 Mon 2017-11-06 14:57:59 CET—Mon 2017-11-06 1
But I didn't know what doest it mean.

Anyway. Thanks.

**Comment by merlijn-sebrechts** [comment]
That means the systemd journal (the log collector) only contains logs since the last boot (which happened on `Mon 2017-11-06 14:57:59`).

Thus, we cannot look at the logs from when `fwupd` failed, because those logs were not saved.

**Comment by gerobum** [comment]
I see.

**Comment by seb128** [comment]
the journal isn't persistant but the logs are stored in /var/log/syslog as well no? that should have records from previous boot (it's being rotated so could be .1)

**Comment by jeremybmerrill** [comment]
Chiming in to say that I had this same bug occur on my Dell XPS 13 (2016), but didn't have persistent logs on. However @galgalesh, your guide at the top of the thread worked perfectly to fix my issue, so thank you!

**Comment by superm1** [comment]
@jeremybmerrill were you on Ubuntu as well?  We need someone to help to verify the SRU that has been filed.

**Comment by jeremybmerrill** [comment]
@superm1 Yes, Ubuntu 17.10. Happy to do what I can to help, just tell me what to do.

**Comment by merlijn-sebrechts** [comment]
@superm1 I think something went wrong, the patch is still not in proposed..

```
sudo apt-get install fwupdate-signed/artful-proposed
[sudo] password for merlijn: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Release ‘artful-proposed’ for ‘fwupdate-signed’ was not found
```

**Comment by superm1** [comment]
@jeremybmerrill Yes so this is the public bug: https://bugs.launchpad.net/ubuntu/+source/fwupd/+bug/1730343
Can you follow the directions on installing the fwupdate-signed and fwupdate packages from proposed?

@galgalesh 
Hmm, I see them in proposed according to: https://launchpad.net/ubuntu/+source/fwupdate and https://launchpad.net/ubuntu/+source/fwupdate-signed

Presumably you've already apt updated and have proposed activated?

**Comment by jeremybmerrill** [comment]
@superm1 Do you know if the bug is such that my system did update the firmware properly, but just didn't boot up correctly afterwards? Or did the system not update the firmware?

I enabled proposed, ran `sudo apt-get install fwupdate/artful-proposed` (and tried to run `sudo apt-get install fwupdate-signed/artful-proposed`, but it said `E: Release 'artful-proposed' for 'fwupdate-signed' was not found` -- same as @galgalesh ).

How do I run the update again, now that I have a new `fwupdate`?

**Comment by superm1** [comment]
@jeremybmerrill yes that's the bug, it didn't boot up afterwards properly.

To confirm you have the latest package can you please run:
`apt-cache policy fwupdate-signed`

IIRC artful-proposed isn't enabled by default, you have to modify `/etc/apt/sources.list` to do it.

After you confirm you have the new package, you can manually download the CAB file from LVFS for your system.

then run:

`fwupdmgr install --allow-reinstall blah.cab`

**Comment by merlijn-sebrechts** [comment]
@superm1 

```
$ apt-cache policy fwupdate-signed
fwupdate-signed:
  Installed: (none)
  Candidate: 1.14+9-2
  Version table:
     1.14+9-2 500
        500 http://us.archive.ubuntu.com/ubuntu artful/main amd64 Packages
        100 /var/lib/dpkg/status
$ apt-cache policy fwupdate
fwupdate:
  Installed: 9-2ubuntu0.17.10.1
  Candidate: 9-2ubuntu0.17.10.1
  Version table:
 *** 9-2ubuntu0.17.10.1 400
        400 http://us.archive.ubuntu.com/ubuntu artful-proposed/main amd64 Packages
        100 /var/lib/dpkg/status
     9-2 500
        500 http://us.archive.ubuntu.com/ubuntu artful/main amd64 Packages
```

1. I uninstalled `fwupdate-signed` and installed `fwupdate` I suspect the "signed" is only relevant for secureboot?
2. I removed _all_ boot options in my UEFI boot menu.
3. I rebooted and it boots into Ubuntu
4. I downloaded the firmware from here: https://fwupd.org/lvfs/devicelist (Are you aware that there are two entries for Latitude 5X80?)
5.  I ran `fwupdmgr install --allow-reinstall <filename>.cab` and rebooted my machine.
6. fwupdate starts, updates, and reboots into Ubuntu.

**So If your assessment of the cause of the bug is correct, then the bug is fixed.**

However there is clearly something wrong with fwupdate-signed since it isn't visible for us in the artful-proposed repos as you can see in the output of the commands up top.

**Comment by superm1** [comment]
Can you confirm the efibootmgr -v output after that list of steps you followed?

**Comment by merlijn-sebrechts** [comment]
```
$ efibootmgr -v
BootCurrent: 0002
Timeout: 2 seconds
BootOrder: 0002,0001
Boot0000* Windows Boot Manager	HD(1,GPT,4076bdbf-fe0f-4db3-85f6-2cab5d6263a3,0x800,0xfa000)/File(\EFI\Microsoft\Boot\bootmgfw.efi)WINDOWS.........x...B.C.D.O.B.J.E.C.T.=.{.9.d.e.a.8.6.2.c.-.5.c.d.d.-.4.e.7.0.-.a.c.c.1.-.f.3.2.b.3.4.4.d.4.7.9.5.}....................
Boot0001* UEFI: SanDisk X400 M.2 2280 512GB, Partition 1	HD(1,GPT,50def640-b2e4-47e9-9456-a8755c5b6cd4,0x800,0x100000)/File(EFI\boot\bootx64.efi)..BO
Boot0002* ubuntu	HD(1,GPT,50def640-b2e4-47e9-9456-a8755c5b6cd4,0x800,0x100000)/File(\EFI\ubuntu\shimx64.efi)
```

I am surprised that windows boot manager shows up here, I don't run Windows..

**Comment by 4l1fe** [comment]
@galgalesh bro, you have saved my life by your guide!

for **dell xps** on **Ubuntu 16.04** there is one more step is to disable secure booting in BIOS because of such problem 
![img_20171120_205123](https://user-images.githubusercontent.com/21095447/33022944-49a98a1e-ce39-11e7-99e0-cebac76e4eea.jpg)

**Comment by superm1** [comment]
@4l1fe there was a problem with the building of fwupdate-signed for some reason on Launchpad.  I just requested it to be rebuilt, hopefully that will fix the problem with secure boot.

@galgalesh 
Thanks, so that confirms that the issue I was trying to fix did get fixed properly.  Would you mind adding a comment to Launchpad and the tag that indicates you verified the fwupdate package?  fwupdate-signed we'll need to adjust something.

**Comment by superm1** [comment]
@galgalesh regarding your comment about two Latitude 5x80 devices, yes it's intended.  There are two different variants of the 5x80's that contain incompatible BIOS binaries.  In that case you need to match the ESRT GUID to the one you have (which it sounds like you were able to successfully or luckily do).

For most people it doesn't affect them because LVFS sorts it out.  It's just when you manually go hunting for the binaries that it could be problematic.

**Comment by 4l1fe** [comment]
@superm1 Can you say if my bootloading depends on a new firmware ? coz it became very very slow after updating. 
`$ systemd-analyze 
Startup finished in 6.016s (firmware) + 5.885s (loader) + 7.954s (kernel) + 3min 328ms (userspace) = 3min 20.185s`

And how can i downgrade the firmware and return previous settings in `Boot sequence` is showed in the first topic?  I know that this is not a problem of `fwupdate` just advice where to go from this point.

**Comment by superm1** [comment]
@4l1fe Better to discuss this in a different forum than an issue.  If you want to downgrade firmware you can download the .EXE and place it on a FAT32 partition or USB disk and flash from the F12 menu.  UEFI capsule downgrades are generally not supported on Dell systems.

**Comment by 4l1fe** [comment]
Thx for the advice. I have solved this problem. It was not related to `fwupdate`.

**Comment by jeremybmerrill** [comment]
@superm1 : I see that the fwupdate-signed version for artful-proposed is now available in the repos. I installed it and tried to install the updates. The installation failed (due to the TPM being owned, or something? Then due to the update supposedly not being for my system -- but these are not fwupdate related, I don't think), but then it rebooted into Ubuntu properly. I'm not sure if this avoided the spot where the problem was or if it reflects a successful fix.

**Comment by superm1** [comment]
@jeremybmerrill can you please confirm your `efibootmgr -v` output?  That will confirm whether the reported problem is fixed or not.

Your other two issues are quite interesting to me though.  I'd like some other details if you can share them.
1. Model number for system
2. `fwupdmgr devices` output
3. Was this a firmware or TPM update you were doing?

**Comment by jeremybmerrill** [comment]
```# efibootmgr -v
BootNext: 0001
BootCurrent: 0003
Timeout: 0 seconds
BootOrder: 0003,0000,0001
Boot0000* Windows Boot Manager	HD(1,GPT,35f0cd73-d921-4ceb-a20a-1c1acf5c6761,0x800,0xfa000)/File(\EFI\Microsoft\Boot\bootmgfw.efi)WINDOWS.........x...B.C.D.O.B.J.E.C.T.=.{.9.d.e.a.8.6.2.c.-.5.c.d.d.-.4.e.7.0.-.a.c.c.1.-.f.3.2.b.3.4.4.d.4.7.9.5.}....4...............
Boot0001* Linux-Firmware-Updater \fwupx64.efi	HD(1,GPT,35f0cd73-d921-4ceb-a20a-1c1acf5c6761,0x800,0xfa000)/File(\EFI\ubuntu\shimx64.efi)\.f.w.u.p.x.6.4...e.f.i...
Boot0003* Ubuntu	PciRoot(0x0)/Pci(0x1d,0x0)/Pci(0x0,0x0)/NVMe(0x1,00-08-0D-03-00-02-6E-8C)/HD(1,GPT,35f0cd73-d921-4ceb-a20a-1c1acf5c6761,0x800,0xfa000)/File(\EFI\ubuntu\grubx64.efi)
Boot000A* UEFI: THNSN5512GPU7 NVMe TOSHIBA 512GB, Partition 1	HD(1,GPT,35f0cd73-d921-4ceb-a20a-1c1acf5c6761,0x800,0xfa000)/File(EFI\Microsoft\Boot\bootmgfw.efi)..BO
```

1. Dell XPS 13 9350
2. output --> https://gist.github.com/jeremybmerrill/bb3d7a4a169de6d85b0c0ad00efc8604
3. Both (it's what the Software Center suggests). 
![screenshot from 2017-12-05 22-27-16](https://user-images.githubusercontent.com/548250/33643185-854cf9ba-da0b-11e7-9e2f-55805cc8295e.png)

Thanks again for all your help!

**Comment by jeremybmerrill** [comment]
@superm1 : Oddly enough, I restarted again (for other reasons) and it seems to have updated the firmware. Not sure what happened the first time.

**Comment by superm1** [comment]
Did it update the tpm too? I think this might be order of events.

**Comment by jeremybmerrill** [comment]
@superm1 It appears to have only updated the BIOS, but it did not update the TPM. (At least -- the Updater still suggests that I update the TPM)

**Comment by superm1** [comment]
I suppose the tpm update won't take due to it being owned now right? Did you take ownership of it?

**Comment by jeremybmerrill** [comment]
Yes, I think that's why it failed. I need to figure out how to take
ownership of it, I just haven't had time

**Comment by superm1** [comment]
Well so it's not supposed to even offer in Ubuntu if it's owned. That's the odd part to me.

**Comment by superm1** [comment]
Well it's not supposed to allow switching modes if owned. I think upgrades within the mode should work though.

**Comment by KoenDG** [comment]
Chiming in, just now had the same issue with a Dell Inspiron 3520, running Ubuntu 16.04 LTS.

Ouput of the commands I found in this thread:

```
efibootmgr -v
BootCurrent: 0002
Timeout: 0 seconds
BootOrder: 0002,0000
Boot0000  Linux-Firmware-Updater \fwupx64.efi	HD(1,GPT,9b1d146c-b8a3-45b6-9076-150bb5292428,0x800,0x12c000)/File(\EFI\ubuntu\shimx64.efi)\.f.w.u.p.x.6.4...e.f.i...
Boot0001* Diskette Drive	BBS(Floppy,Diskette Drive,0x0)..BO
Boot0002* Ubuntu	PciRoot(0x0)/Pci(0x17,0x0)/Sata(0,65535,0)/HD(1,GPT,9b1d146c-b8a3-45b6-9076-150bb5292428,0x800,0x12c000)/File(\EFI\ubuntu\grubx64.efi)
Boot0003* USB Storage Device	BBS(USB,USB Storage Device,0x0)..BO
Boot0004* CD/DVD/CD-RW Drive	BBS(CDROM,CD/DVD/CD-RW Drive,0x0)..BO
Boot0005* Onboard NIC	BBS(Network,IBA CL Slot 00FE v0109,0x0)..BO
Boot0006* M.2 SATA SSD	BBS(HD,P0: Micron 1100 SATA 256GB,0x0)..BO
Boot0007* UEFI: Micron 1100 SATA 256GB, Partition 1	HD(1,GPT,9b1d146c-b8a3-45b6-9076-150bb5292428,0x800,0x12c000)/File(EFI\boot\bootx64.efi)..BO

```
```

sudo apt-cache policy fwupdate-signed 
fwupdate-signed:
  Installed: 1.11.1+0.5-2ubuntu5
  Candidate: 1.11.1+0.5-2ubuntu5
  Version table:
 *** 1.11.1+0.5-2ubuntu5 500
        500 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     1.11+0.5-2ubuntu4 500
        500 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages

sudo apt-cache policy fwupdate
fwupdate:
  Installed: 0.5-2ubuntu5
  Candidate: 0.5-2ubuntu5
  Version table:
 *** 0.5-2ubuntu5 500
        500 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     0.5-2ubuntu4 500
        500 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages

sudo apt-cache policy fwupdate-amd64-signed 
fwupdate-amd64-signed:
  Installed: (none)
  Candidate: 1.11.1+0.5-2ubuntu5
  Version table:
     1.11.1+0.5-2ubuntu5 500
        500 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages
     1.11+0.5-2ubuntu4 500
        500 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
```

and

```
sudo journalctl --list-boots
 0 8c2d64526f214aa184b470acd3b00806 Thu 2017-12-14 20:10:13 CET—Thu 2017-12-14 20:24:16 CET
```

Hope it helps.

**Comment by superm1** [comment]
@KoenDG Can you please add a comment to https://bugs.launchpad.net/ubuntu/+source/fwupd/+bug/1730343

The Ubuntu archive admin needs to release the uploaded package for 16.04.

**Comment by KoenDG** [comment]
@superm1 Comment made.

**Comment by superm1** [comment]
@KoenDG would you be able to test the 16.04 package as it's been accepted by that admin?

**Comment by KoenDG** [comment]
@superm1 I followed the steps found here: https://wiki.ubuntu.com/Testing/EnableProposed

And selected fwupdate and fwupdate-signed from aptitude(which were not both in the same part of the tree for some reason).

3 packages were selected for update, fwupdate, fwupdate-signed and the library behind it, I already forgot the name.

Install showed no errors. I then performed `sudo shutdown -r now` and this had no error. No actual firmware update either, it just restarted the system. same with `shutdown -h`.

`dpkg -l fwupdate | cat` shows version 0.5-2ubuntu6 installed for amd64

I don't know if there's something else I should test. There isn't actually a firmware update available so I don't know how to test it further.

**Comment by superm1** [comment]
@KoenDG thanks for looking.  Yes they're two separate packages due to how the signing works in Ubuntu.

You can download the latest CAB file for your system and install with `fwupdmgr install <blah.cab> --allow-reinstall`
If you can succesfully boot after installing that way then I would deem it a successful test (and please mark it on the Launchpad bug too).

**Comment by KoenDG** [comment]
@superm1 I can't get it to work.

I had to look for the cab file in my download cache, it was still there. The Dell website isn't offering it for download anywhere.

I did the command as instructed, got the output saying an upgrade was scheduled.

I tried both `shutdown -r` and going to the Ubuntu Software menu and doing the upgrade&restart from there.

I tried it with and without `--allow-reinstall`. I tried it with the cab file as a normal file and as an executable file.

In all instances, a regular reboot happens and nothing else.

`dmidecode` still says the BIOS is on version 1.7.5, dating 11/12/2017

Not sure why it's not picking up the upgrade.

**Comment by superm1** [comment]
The CAB file comes from LVFS not from the Dell site, so that's why you couldn't find it there.  It's good you had it in your cache though.

After you have scheduled it but before rebooting, can you please share the output of:
```
# efibootmgr -v
```

In `dmidecode` output the date should stay the same even if you were successful.  It's the date the BIOS was built not the date that it was flashed.  To query the date of the last flash you would have to look elsewhere.

**Comment by KoenDG** [comment]
@superm1 As requested:

```
# efibootmgr -v
BootNext: 0008
BootCurrent: 0002
Timeout: 0 seconds
BootOrder: 0002,0000,0008
Boot0000  Linux-Firmware-Updater \fwupx64.efi	HD(1,GPT,9b1d146c-b8a3-45b6-9076-150bb5292428,0x800,0x12c000)/File(\EFI\ubuntu\shimx64.efi)\.f.w.u.p.x.6.4...e.f.i...
Boot0001* Diskette Drive	BBS(Floppy,Diskette Drive,0x0)..BO
Boot0002* ubuntu	HD(1,GPT,9b1d146c-b8a3-45b6-9076-150bb5292428,0x800,0x12c000)/File(\EFI\ubuntu\shimx64.efi)
Boot0003* USB Storage Device	BBS(USB,USB Storage Device,0x0)..BO
Boot0004* CD/DVD/CD-RW Drive	BBS(CDROM,CD/DVD/CD-RW Drive,0x0)..BO
Boot0005* Onboard NIC	BBS(Network,IBA CL Slot 00FE v0109,0x0)..BO
Boot0006* M.2 SATA SSD	BBS(HD,P0: Micron 1100 SATA 256GB,0x0)..BO
Boot0007* UEFI: Micron 1100 SATA 256GB, Partition 1	HD(1,GPT,9b1d146c-b8a3-45b6-9076-150bb5292428,0x800,0x12c000)/File(EFI\boot\bootx64.efi)..BO
Boot0008* Linux-Firmware-Updater \fwupx64.efi	HD(1,GPT,9b1d146c-b8a3-45b6-9076-150bb5292428,0x800,0x12c000)/File(\EFI\ubuntu\shimx64.efi)\.f.w.u.p.x.6.4...e.f.i...
```

**Comment by superm1** [comment]
Hmm, looks like it did the correct thing to me.  And after that you don't see the fwupx64.efi quick between post and GRUB coming up pop up?  
Do you have secure boot enabled?  Can you confirm the checksums of /boot/efi/efi/ubuntu/fwupx64.efi?

**Comment by KoenDG** [comment]
Nothing comes up. Secure boot is disabled

MD5: 1a68d9b11532c19640b4a2eeeee4fd80  /boot/efi/efi/ubuntu/fwupx64.efi
SHA256: 52d202634650ae9196a9bcf79c6a689f15feb82be4f4cc5462a0dc1aca64456e  /boot/efi/efi/ubuntu/fwupx64.efi

Could this be related to the fact that I had to use the fix given in the top post here, when this happened to me? So I selected the ubuntu shimx64.efi and that's still selected?

**Comment by superm1** [comment]
That is the correct checksum.  Something that stick out is that you have two different Linux Firmware Updater entries.  I wonder if that's throwing something off.

Can you please try to delete both with efibootmgr and try again?

**Comment by KoenDG** [comment]
@superm1 I executed `sudo efibootmgr -D` which deletes duplicates.

Attempt the update now gave me a new message: Cannot install update when not on AC power.

So that's progress. I don't have my AC adapter with me so it'll have to wait until tomorrow.

**Comment by superm1** [comment]
@KoenDG That message came from the Dell flash screen or from fwupd?  If it's from the Dell flash screen that's great news and it means that the duplicates were the root cause.

**Comment by KoenDG** [comment]
@superm1 Sorry, it's from fwupdmgr. The flash screen just saying "Bootin in insecure mode".

```
... .cache/gnome-software/3.20/firmware/4a89bbb6bd769fdfc315c37db55a74b8e7f25768-firmware.Latitude_5x80_Precision_3520_1.8.1H.wu.cab --allow-reinstall
 * Decompressing firmware
Retrying as an offline update...
 * Idle
 * Decompressing firmware
Cannot install update when not on AC power
```

**Comment by superm1** [comment]
Ah OK, so then it doesn't tell anything interesting yet.  I guess we'll see tomorrow then.

**Comment by KoenDG** [comment]
@superm1 Just tried with the AC plugged in, nothing happens.

Tried it with the 1.7.5 and the 1.8.1, restart from commandline, restart from the "Ubuntu Software" GUI, nothing happens.

It just goes by the DELL logo, I see "Booting in insecure mode" in the top left and then it starts normally.

**Comment by superm1** [comment]
Ok so that's definitely a failure then.  I'll need to get a 16.04 box setup to dig into what's going wrong.

**Comment by KoenDG** [comment]
@superm1 Could this have something to do with having followed the guide at the top of this thread? Do I need to revert that last step?

**Comment by superm1** [comment]
@KoenDG I don't think it should have, it looked like in your above efibootmgr output that you had not followed the guide (you picked `shimx64.efi` not `grubx64.efi`)
```
Boot0002* ubuntu	HD(1,GPT,9b1d146c-b8a3-45b6-9076-150bb5292428,0x800,0x12c000)/File(\EFI\ubuntu\shimx64.efi)
```

**Comment by KoenDG** [comment]
@superm1 It appears that after I did `efibootmgr -D` it removed the duplicate but left the BootNext on a non-existing entry.


```
# efibootmgr -v
BootNext: 0008
BootCurrent: 0002
Timeout: 0 seconds
BootOrder: 0002,0000
Boot0000  Linux-Firmware-Updater \fwupx64.efi	HD(1,GPT,9b1d146c-b8a3-45b6-9076-150bb5292428,0x800,0x12c000)/File(\EFI\ubuntu\shimx64.efi)\.f.w.u.p.x.6.4...e.f.i...
Boot0001* Diskette Drive	BBS(Floppy,Diskette Drive,0x0)..BO
Boot0002* ubuntu	HD(1,GPT,9b1d146c-b8a3-45b6-9076-150bb5292428,0x800,0x12c000)/File(\EFI\ubuntu\shimx64.efi)
Boot0003* USB Storage Device	BBS(USB,USB Storage Device,0x0)..BO
Boot0004* CD/DVD/CD-RW Drive	BBS(CDROM,CD/DVD/CD-RW Drive,0x0)..BO
Boot0005* Onboard NIC	BBS(Network,IBA CL Slot 00FE v0109,0x0)..BO
Boot0006* M.2 SATA SSD	BBS(HD,P0: Micron 1100 SATA 256GB,0x0)..BO
Boot0007* UEFI: Micron 1100 SATA 256GB, Partition 1	HD(1,GPT,9b1d146c-b8a3-45b6-9076-150bb5292428,0x800,0x12c000)/File(EFI\boot\bootx64.efi)..BO
```

**Comment by superm1** [comment]
@KoenDG 
I still see a stray entry there, can you please manually delete the 0000 entry and the BootNext entry then?

When you run the update it will create a new entry for you and set it appropriately.

**Comment by KoenDG** [comment]
Alright, I did the cleanup as follow:

```# efibootmgr -v
BootNext: 0008
BootCurrent: 0002
Timeout: 0 seconds
BootOrder: 0002,0000
Boot0000  Linux-Firmware-Updater \fwupx64.efi   HD(1,GPT,9b1d146c-b8a3-45b6-9076-150bb5292428,0x800,0x12c000)/File(\EFI\ubuntu\shimx64.efi)\.f.w.u.p.x.6.4...e.f.i...
Boot0001* Diskette Drive    BBS(Floppy,Diskette Drive,0x0)..BO
Boot0002* ubuntu    HD(1,GPT,9b1d146c-b8a3-45b6-9076-150bb5292428,0x800,0x12c000)/File(\EFI\ubuntu\shimx64.efi)
Boot0003* USB Storage Device    BBS(USB,USB Storage Device,0x0)..BO
Boot0004* CD/DVD/CD-RW Drive    BBS(CDROM,CD/DVD/CD-RW Drive,0x0)..BO
Boot0005* Onboard NIC   BBS(Network,IBA CL Slot 00FE v0109,0x0)..BO
Boot0006* M.2 SATA SSD  BBS(HD,P0: Micron 1100 SATA 256GB,0x0)..BO
Boot0007* UEFI: Micron 1100 SATA 256GB, Partition 1 HD(1,GPT,9b1d146c-b8a3-45b6-9076-150bb5292428,0x800,0x12c000)/File(EFI\boot\bootx64.efi)..BO

# efibootmgr -b 0 -B
BootNext: 0008
BootCurrent: 0002
Timeout: 0 seconds
BootOrder: 0002
Boot0001* Diskette Drive
Boot0002* ubuntu
Boot0003* USB Storage Device
Boot0004* CD/DVD/CD-RW Drive
Boot0005* Onboard NIC
Boot0006* M.2 SATA SSD
Boot0007* UEFI: Micron 1100 SATA 256GB, Partition 1

# efibootmgr -N
BootCurrent: 0002
Timeout: 0 seconds
BootOrder: 0002
Boot0001* Diskette Drive
Boot0002* ubuntu
Boot0003* USB Storage Device
Boot0004* CD/DVD/CD-RW Drive
Boot0005* Onboard NIC
Boot0006* M.2 SATA SSD
Boot0007* UEFI: Micron 1100 SATA 256GB, Partition 1
```

After setting the reinstall for 1.7.5, it did indeed create the new option:

```# efibootmgr -v
BootNext: 0000
BootCurrent: 0002
Timeout: 0 seconds
BootOrder: 0002,0000
Boot0000* Linux-Firmware-Updater \fwupx64.efi	HD(1,GPT,9b1d146c-b8a3-45b6-9076-150bb5292428,0x800,0x12c000)/File(\EFI\ubuntu\shimx64.efi)\.f.w.u.p.x.6.4...e.f.i...
Boot0001* Diskette Drive	BBS(Floppy,Diskette Drive,0x0)..BO
Boot0002* ubuntu	HD(1,GPT,9b1d146c-b8a3-45b6-9076-150bb5292428,0x800,0x12c000)/File(\EFI\ubuntu\shimx64.efi)
Boot0003* USB Storage Device	BBS(USB,USB Storage Device,0x0)..BO
Boot0004* CD/DVD/CD-RW Drive	BBS(CDROM,CD/DVD/CD-RW Drive,0x0)..BO
Boot0005* Onboard NIC	BBS(Network,IBA CL Slot 00FE v0109,0x0)..BO
Boot0006* M.2 SATA SSD	BBS(HD,P0: Micron 1100 SATA 256GB,0x0)..BO
Boot0007* UEFI: Micron 1100 SATA 256GB, Partition 1	HD(1,GPT,9b1d146c-b8a3-45b6-9076-150bb5292428,0x800,0x12c000)/File(EFI\boot\bootx64.efi)..BO
```

Here goes.

**Comment by KoenDG** [comment]
@superm1 Looks like a failure.

I took a picture with my phone: https://www.dropbox.com/s/6r6zeadqakbtjg5/2018-01-04%2023.35.59-1.jpg?dl=0

Hope it's readable.

After that it just went on with a regular boot.

**Comment by superm1** [comment]
Ah darn.  OK so some other patches really need to come back with it then still, that's unfortunate.
Can you please share that link on Launchpad and mark it verification failed?  I'll need to dig into what else needs to come back.

**Comment by KoenDG** [comment]
@superm1 Comment made. Not sure how to mark as failed.

EDIT: Ah hang on I found it. Updated the tags at the top.

**Comment by superm1** [comment]
So this issue from an upstream fwupdate perspective is fixed, I'm going to close it on Github.  From an Ubuntu perspective, the SRU still needs to be done/fixed for xenial/16.04.

Anyone who encounters this outside of Ubuntu with the older fwupdate, please file retry with the latest release (10) and open a new bug referencing this one if you have problems.

**Comment by superm1** [comment]
@galgalesh Would you  be able to bring your content from the first post about how to recover over to a Wiki page?  I think it would be good to have it there so it's not lost in Github bug history if someone encounters this in the future.

**Comment by superm1** [comment]
@galgalesh thanks for making the wiki page.
@KoenDG 16.04 fix has landed now in -proposed.  I personally verified it on XPS 9350.

**Comment by KoenDG** [comment]
@superm1 Neat, I'll try it out this weekend.

**Comment by KoenDG** [comment]
@superm1 Update success. Firmware update from 1.7.5 to 1.8.1 was successful.

**Comment by superm1** [comment]
That's great to hear, thanks.  I'm going to lock this issue.

Anyone who encounters this issue in the future:
1. If you need help recovering, please follow the steps outlined here:
https://github.com/rhboot/fwupdate/wiki/How-to-recover-from-%22no-bootable-devices-found%22-and-%22No-updates-to-process%22

2. If you are on Ubuntu, please make sure that you are in a version containing the fix 
(details in https://bugs.launchpad.net/ubuntu/+source/fwupd/+bug/1730343)

**If you are on Ubuntu and have that version or newer or you encounter it on any other distro, please file a new issue.**
