### ISSUE TITLE
Respect CFLAGS and LDFLAGS

### ISSUE THREAD

**Issue by tpgxyz** [vathpela/fwup#9]
Hi,

please merge this patch, as currently global CFLAGS and LDFLAGS are not respected by makefiles

https://github.com/OpenMandrivaAssociation/fwupdate/blob/master/fwupdate-0.4-respect-cflags-and-ldflags.patch

Thanks.

**Comment by vathpela** [comment]
Done, thanks.  In the future, it'd be quite a bit easier if you pushed a fork of the repo someplace, so I can pull instead of fish patches out of other patches. But nevertheless, thanks!
